version: "2"
services:
  service:
    build: ./service
    volumes:
      - ./service:/app
    ports:
      - "8080:8080"
  app:
    build: ./app
    volumes:
      - ./app:/app
    ports:
      - "3000:3000"
